// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpQinKffQHNkVNI7d6vZAgFfp7irogPY',
    appId: '1:456510707392:web:57b8e041cd2155c3427f25',
    messagingSenderId: '456510707392',
    projectId: 'espanol-pro-xamide',
    authDomain: 'espanol-pro-xamide.firebaseapp.com',
    storageBucket: 'espanol-pro-xamide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcaDTVHY4fGUK90JkMs0VU-IIP3q8RpRE',
    appId: '1:456510707392:android:e95dc57d52d1929c427f25',
    messagingSenderId: '456510707392',
    projectId: 'espanol-pro-xamide',
    storageBucket: 'espanol-pro-xamide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlqSbdW20pvFrncT3W3YC-pDDFIOLNZs',
    appId: '1:456510707392:ios:15797c93f8df5d53427f25',
    messagingSenderId: '456510707392',
    projectId: 'espanol-pro-xamide',
    storageBucket: 'espanol-pro-xamide.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJlqSbdW20pvFrncT3W3YC-pDDFIOLNZs',
    appId: '1:456510707392:ios:15797c93f8df5d53427f25',
    messagingSenderId: '456510707392',
    projectId: 'espanol-pro-xamide',
    storageBucket: 'espanol-pro-xamide.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwpQinKffQHNkVNI7d6vZAgFfp7irogPY',
    appId: '1:456510707392:web:a347e3389ad0cf53427f25',
    messagingSenderId: '456510707392',
    projectId: 'espanol-pro-xamide',
    authDomain: 'espanol-pro-xamide.firebaseapp.com',
    storageBucket: 'espanol-pro-xamide.firebasestorage.app',
  );
}
